name: CI

on: [push]

jobs:
 test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 14,OS=16.2']
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: latest-stable
    - name: Setup environment
      uses: ruby/setup-ruby@v1.84.0
      with:
        ruby-version: '3.0.1'
        bundler-cache: true
    - name: Test StylableSwiftUI
      shell: bash
      run: |
        pushd Example
        set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace ${workspace} -scheme ${scheme} -destination "${destination}"
        popd
        pod lib lint --allow-warnings
      env:
        destination: ${{ matrix.destination }}
        scheme: "StylableSwiftUI-Example"
        workspace: "StylableSwiftUI.xcworkspace"
        ONLY_ACTIVE_ARCH: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO" 
